In [1]:
import numpy as np
import pandas as pd
from bs4 import BeautifulSoup as bs
import requests

In [2]:
movie_title = []
movie_year = []
movie_length = []
movie_genre = []
movie_rating = []
movie_des = []
movie_crew = []
movie_poster = []

In [3]:
number=['1','251','501','751']
for num in number:
    r = requests.get("https://www.imdb.com/search/title/?groups=top_1000&sort=user_rating,desc&count=250&start="+num+"&ref_=adv_nxt")

    #convert into a beatuful soup object
    soup = bs(r.content)
    
    imdb_table = soup.find(class_ = "lister list detail sub-list")
    
    
    movie_title_coloumn = imdb_table.find_all(class_ = "lister-item-header")
    for row in movie_title_coloumn:
        title = row.a.text
        movie_title.append(title)
        
    
    movie_year_coloumn = imdb_table.find_all(class_ = "lister-item-year text-muted unbold")
    for row in movie_year_coloumn:
        year = row.text
        movie_year.append(year)
        
    
    movie_length_coloumn = imdb_table.find_all(class_ = "runtime")
    for row in movie_length_coloumn:
        length = row.text
        movie_length.append(length)
        
    
    movie_genre_coloumn = imdb_table.find_all(class_ = "genre")
    for row in movie_genre_coloumn:
        genre = row.text
        movie_genre.append(genre)
        
        
    movie_rating_coloumn = imdb_table.find_all(class_ = "inline-block ratings-imdb-rating")
    for row in movie_rating_coloumn:
        rating = row.strong.text
        movie_rating.append(rating)
        
        
    movie_des_coloumn = imdb_table.find_all('p',class_ = "text-muted" )
    for row in movie_des_coloumn[1::2]:
        des = row.text
        movie_des.append(des)
        
    
    movie_crew_column = imdb_table.find_all('p' , class_ = "")
    for row in movie_crew_column:
        crew = row.text
        movie_crew.append(crew)
        
    movie_poster_column = imdb_table.find_all("img") 
    for image in movie_poster_column:
        movie_poster.append(image['loadlate'])

In [4]:
len(movie_title)

1000

In [5]:
len(movie_year)

1000

In [6]:
len(movie_length)

1000

In [7]:
len(movie_genre)

1000

In [8]:
len(movie_rating)

1000

In [9]:
len(movie_des)

1000

In [10]:
len(movie_crew)

1000

In [11]:
dict ={'movie_title' : movie_title,
       'movie_year' : movie_year,
       'movie_length' : movie_length,
       'movie_genre' : movie_genre,
       'movie_rating' : movie_rating,
       'movie_des' : movie_des,
       'movie_crew' : movie_crew,
       'movie_poster': movie_poster
      }
df = pd.DataFrame(dict)
df

,movie_title,movie_year,movie_length,movie_genre,movie_rating,movie_des,movie_crew,movie_poster
0,The Shawshank Redemption,(1994),142 min,\nDrama,9.3,"\nOver the course of several years, two convic...",\n Director:\nFrank Darabont\n| \n Stars...,https://m.media-amazon.com/images/M/MV5BMDFkYT...
1,The Godfather,(1972),175 min,"\nCrime, Drama",9.2,\nThe aging patriarch of an organized crime dy...,\n Director:\nFrancis Ford Coppola\n| \n ...,https://m.media-amazon.com/images/M/MV5BM2MyNj...
2,The Dark Knight,(2008),152 min,"\nAction, Crime, Drama",9.0,\nWhen the menace known as the Joker wreaks ha...,\n Director:\nChristopher Nolan\n| \n St...,https://m.media-amazon.com/images/M/MV5BMTMxNT...
3,Schindler's List,(1993),195 min,"\nBiography, Drama, History",9.0,\nIn German-occupied Poland during World War I...,\n Director:\nSteven Spielberg\n| \n Sta...,https://m.media-amazon.com/images/M/MV5BNDE4OT...
4,The Godfather Part II,(1974),202 min,"\nCrime, Drama",9.0,\nThe early life and career of Vito Corleone i...,\n Director:\nFrancis Ford Coppola\n| \n ...,https://m.media-amazon.com/images/M/MV5BMWMwMG...
...,...,...,...,...,...,...,...,...
995,The Station Agent,(2003),89 min,"\nComedy, Drama",7.6,"\nWhen his only friend dies, a man born with d...",\n Director:\nTom McCarthy\n| \n Stars:\...,https://m.media-amazon.com/images/M/MV5BMTUzND...
996,Repulsion,(1965),105 min,"\nDrama, Horror, Thriller",7.6,\nA sex-repulsed woman who disapproves of her ...,\n Director:\nRoman Polanski\n| \n Stars...,https://m.media-amazon.com/images/M/MV5BMzdiZm...
997,Les yeux sans visage,(1960),90 min,"\nDrama, Horror",7.6,\nA surgeon causes an accident which leaves hi...,\n Director:\nGeorges Franju\n| \n Stars...,https://m.media-amazon.com/images/M/MV5BNjVjND...
998,Shine,(1996),105 min,"\nBiography, Drama, Music",7.6,"\nPianist David Helfgott, driven by his father...",\n Director:\nScott Hicks\n| \n Stars:\n...,https://m.media-amazon.com/images/M/MV5BNTNlZD...
999,Celda 211,(2009),113 min,"\nAction, Crime, Drama",7.6,\nThe story of two men on different sides of a...,\n Director:\nDaniel Monzón\n| \n Stars:...,https://m.media-amazon.com/images/M/MV5BMjI2OD...

In [12]:
df['movie_year'] = df['movie_year'].apply(lambda x: x.replace('(' , '').replace(')','').replace('I' , '').replace('II' , '').replace('III' , ''))

In [13]:
df.head()

,movie_title,movie_year,movie_length,movie_genre,movie_rating,movie_des,movie_crew,movie_poster
0,The Shawshank Redemption,1994,142 min,\nDrama,9.3,"\nOver the course of several years, two convic...",\n Director:\nFrank Darabont\n| \n Stars...,https://m.media-amazon.com/images/M/MV5BMDFkYT...
1,The Godfather,1972,175 min,"\nCrime, Drama",9.2,\nThe aging patriarch of an organized crime dy...,\n Director:\nFrancis Ford Coppola\n| \n ...,https://m.media-amazon.com/images/M/MV5BM2MyNj...
2,The Dark Knight,2008,152 min,"\nAction, Crime, Drama",9.0,\nWhen the menace known as the Joker wreaks ha...,\n Director:\nChristopher Nolan\n| \n St...,https://m.media-amazon.com/images/M/MV5BMTMxNT...
3,Schindler's List,1993,195 min,"\nBiography, Drama, History",9.0,\nIn German-occupied Poland during World War I...,\n Director:\nSteven Spielberg\n| \n Sta...,https://m.media-amazon.com/images/M/MV5BNDE4OT...
4,The Godfather Part II,1974,202 min,"\nCrime, Drama",9.0,\nThe early life and career of Vito Corleone i...,\n Director:\nFrancis Ford Coppola\n| \n ...,https://m.media-amazon.com/images/M/MV5BMWMwMG...

In [14]:
df['movie_genre'] = df['movie_genre'].apply(lambda x: x.replace('\n' , ''))
df['movie_des'] = df['movie_des'].apply(lambda x: x.replace('\n' , ''))
df['movie_length'] = df['movie_length'].apply(lambda x: x.replace('min' , ''))
df['movie_crew'] = df['movie_crew'].apply(lambda x: x.replace('\n' , ''))

In [15]:
df

,movie_title,movie_year,movie_length,movie_genre,movie_rating,movie_des,movie_crew,movie_poster
0,The Shawshank Redemption,1994,142,Drama,9.3,"Over the course of several years, two convicts...",Director:Frank Darabont| Stars:Tim Rob...,https://m.media-amazon.com/images/M/MV5BMDFkYT...
1,The Godfather,1972,175,"Crime, Drama",9.2,The aging patriarch of an organized crime dyna...,Director:Francis Ford Coppola| Stars:M...,https://m.media-amazon.com/images/M/MV5BM2MyNj...
2,The Dark Knight,2008,152,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,Director:Christopher Nolan| Stars:Chri...,https://m.media-amazon.com/images/M/MV5BMTMxNT...
3,Schindler's List,1993,195,"Biography, Drama, History",9.0,"In German-occupied Poland during World War II,...",Director:Steven Spielberg| Stars:Liam ...,https://m.media-amazon.com/images/M/MV5BNDE4OT...
4,The Godfather Part II,1974,202,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,Director:Francis Ford Coppola| Stars:A...,https://m.media-amazon.com/images/M/MV5BMWMwMG...
...,...,...,...,...,...,...,...,...
995,The Station Agent,2003,89,"Comedy, Drama",7.6,"When his only friend dies, a man born with dwa...",Director:Tom McCarthy| Stars:Peter Din...,https://m.media-amazon.com/images/M/MV5BMTUzND...
996,Repulsion,1965,105,"Drama, Horror, Thriller",7.6,A sex-repulsed woman who disapproves of her si...,Director:Roman Polanski| Stars:Catheri...,https://m.media-amazon.com/images/M/MV5BMzdiZm...
997,Les yeux sans visage,1960,90,"Drama, Horror",7.6,A surgeon causes an accident which leaves his ...,Director:Georges Franju| Stars:Pierre ...,https://m.media-amazon.com/images/M/MV5BNjVjND...
998,Shine,1996,105,"Biography, Drama, Music",7.6,"Pianist David Helfgott, driven by his father a...",Director:Scott Hicks| Stars:Geoffrey R...,https://m.media-amazon.com/images/M/MV5BNTNlZD...
999,Celda 211,2009,113,"Action, Crime, Drama",7.6,The story of two men on different sides of a p...,Director:Daniel Monzón| Stars:Luis Tos...,https://m.media-amazon.com/images/M/MV5BMjI2OD...

In [16]:
df[['director_name' , 'stars_name']] = df['movie_crew'].apply(lambda x : pd.Series(str(x).split('|')))

In [17]:
df.head()

,movie_title,movie_year,movie_length,movie_genre,movie_rating,movie_des,movie_crew,movie_poster,director_name,stars_name
0,The Shawshank Redemption,1994,142,Drama,9.3,"Over the course of several years, two convicts...",Director:Frank Darabont| Stars:Tim Rob...,https://m.media-amazon.com/images/M/MV5BMDFkYT...,Director:Frank Darabont,"Stars:Tim Robbins, Morgan Freeman, Bob Gu..."
1,The Godfather,1972,175,"Crime, Drama",9.2,The aging patriarch of an organized crime dyna...,Director:Francis Ford Coppola| Stars:M...,https://m.media-amazon.com/images/M/MV5BM2MyNj...,Director:Francis Ford Coppola,"Stars:Marlon Brando, Al Pacino, James Caa..."
2,The Dark Knight,2008,152,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,Director:Christopher Nolan| Stars:Chri...,https://m.media-amazon.com/images/M/MV5BMTMxNT...,Director:Christopher Nolan,"Stars:Christian Bale, Heath Ledger, Aaron..."
3,Schindler's List,1993,195,"Biography, Drama, History",9.0,"In German-occupied Poland during World War II,...",Director:Steven Spielberg| Stars:Liam ...,https://m.media-amazon.com/images/M/MV5BNDE4OT...,Director:Steven Spielberg,"Stars:Liam Neeson, Ralph Fiennes, Ben Kin..."
4,The Godfather Part II,1974,202,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,Director:Francis Ford Coppola| Stars:A...,https://m.media-amazon.com/images/M/MV5BMWMwMG...,Director:Francis Ford Coppola,"Stars:Al Pacino, Robert De Niro, Robert D..."

In [18]:
df = df.drop(['movie_crew'],axis=1)
df['director_name'] = df['director_name'].apply(lambda x: x.replace('Director:' , '').replace(' ' , '').replace('Directors:' , ''))
df['stars_name'] = df['stars_name'].apply(lambda x: x.replace('Stars:' , '').replace(' ' , ''))
df

,movie_title,movie_year,movie_length,movie_genre,movie_rating,movie_des,movie_poster,director_name,stars_name
0,The Shawshank Redemption,1994,142,Drama,9.3,"Over the course of several years, two convicts...",https://m.media-amazon.com/images/M/MV5BMDFkYT...,FrankDarabont,"TimRobbins,MorganFreeman,BobGunton,WilliamSadler"
1,The Godfather,1972,175,"Crime, Drama",9.2,The aging patriarch of an organized crime dyna...,https://m.media-amazon.com/images/M/MV5BM2MyNj...,FrancisFordCoppola,"MarlonBrando,AlPacino,JamesCaan,DianeKeaton"
2,The Dark Knight,2008,152,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,https://m.media-amazon.com/images/M/MV5BMTMxNT...,ChristopherNolan,"ChristianBale,HeathLedger,AaronEckhart,Michael..."
3,Schindler's List,1993,195,"Biography, Drama, History",9.0,"In German-occupied Poland during World War II,...",https://m.media-amazon.com/images/M/MV5BNDE4OT...,StevenSpielberg,"LiamNeeson,RalphFiennes,BenKingsley,CarolineGo..."
4,The Godfather Part II,1974,202,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,https://m.media-amazon.com/images/M/MV5BMWMwMG...,FrancisFordCoppola,"AlPacino,RobertDeNiro,RobertDuvall,DianeKeaton"
...,...,...,...,...,...,...,...,...,...
995,The Station Agent,2003,89,"Comedy, Drama",7.6,"When his only friend dies, a man born with dwa...",https://m.media-amazon.com/images/M/MV5BMTUzND...,TomMcCarthy,"PeterDinklage,PatriciaClarkson,BobbyCannavale,..."
996,Repulsion,1965,105,"Drama, Horror, Thriller",7.6,A sex-repulsed woman who disapproves of her si...,https://m.media-amazon.com/images/M/MV5BMzdiZm...,RomanPolanski,"CatherineDeneuve,IanHendry,JohnFraser,YvonneFu..."
997,Les yeux sans visage,1960,90,"Drama, Horror",7.6,A surgeon causes an accident which leaves his ...,https://m.media-amazon.com/images/M/MV5BNjVjND...,GeorgesFranju,"PierreBrasseur,AlidaValli,JulietteMayniel,Alex..."
998,Shine,1996,105,"Biography, Drama, Music",7.6,"Pianist David Helfgott, driven by his father a...",https://m.media-amazon.com/images/M/MV5BNTNlZD...,ScottHicks,"GeoffreyRush,ArminMueller-Stahl,JustinBraine,S..."
999,Celda 211,2009,113,"Action, Crime, Drama",7.6,The story of two men on different sides of a p...,https://m.media-amazon.com/images/M/MV5BMjI2OD...,DanielMonzón,"LuisTosar,AlbertoAmmann,AntonioResines,ManuelM..."

In [19]:
df['movie_title'] = df['movie_title'].str.strip()

In [20]:
df['movie_title']

0      The Shawshank Redemption
1                 The Godfather
2               The Dark Knight
3              Schindler's List
4         The Godfather Part II
                 ...
995           The Station Agent
996                   Repulsion
997        Les yeux sans visage
998                       Shine
999                   Celda 211
Name: movie_title, Length: 1000, dtype: object

In [21]:
df['movie_title'] = df['movie_title'].astype(str) 
df['movie_year'] = df['movie_year'].astype(int)
df['movie_length'] = df['movie_length'].astype(int) 
df['movie_genre'] = df['movie_genre'].astype(str) 
df['movie_rating'] = df['movie_rating'].astype(float) 
df['movie_des'] = df['movie_des'].astype(str) 
df['director_name'] = df['director_name'].astype(str) 
df['stars_name'] = df['stars_name'].astype(str)

In [22]:
df.dtypes

movie_title       object
movie_year         int32
movie_length       int32
movie_genre       object
movie_rating     float64
movie_des         object
movie_poster      object
director_name     object
stars_name        object
dtype: object

In [23]:
df.isnull().sum()

movie_title      0
movie_year       0
movie_length     0
movie_genre      0
movie_rating     0
movie_des        0
movie_poster     0
director_name    0
stars_name       0
dtype: int64

In [24]:
df.duplicated().sum()

0

In [25]:
df.to_csv('IMDB_TOP1000.csv')

In [26]:
df['tags'] = df['movie_des'] + df['movie_genre'] + df['director_name'] + df['stars_name']

In [27]:
df['tags'] = df['tags'].apply(lambda x : x.lower())

In [28]:
df['tags'][110]

"after a daring mission to rescue han solo from jabba the hutt, the rebels dispatch to endor to destroy the second death star. meanwhile, luke struggles to help darth vader back from the dark side without falling into the emperor's trap.action, adventure, fantasy            richardmarquandmarkhamill,harrisonford,carriefisher,billydeewilliams"

In [29]:
new_df = df[['movie_title' ,'tags' , 'movie_poster']]

In [30]:
new_df

,movie_title,tags,movie_poster
0,The Shawshank Redemption,"over the course of several years, two convicts...",https://m.media-amazon.com/images/M/MV5BMDFkYT...
1,The Godfather,the aging patriarch of an organized crime dyna...,https://m.media-amazon.com/images/M/MV5BM2MyNj...
2,The Dark Knight,when the menace known as the joker wreaks havo...,https://m.media-amazon.com/images/M/MV5BMTMxNT...
3,Schindler's List,"in german-occupied poland during world war ii,...",https://m.media-amazon.com/images/M/MV5BNDE4OT...
4,The Godfather Part II,the early life and career of vito corleone in ...,https://m.media-amazon.com/images/M/MV5BMWMwMG...
...,...,...,...
995,The Station Agent,"when his only friend dies, a man born with dwa...",https://m.media-amazon.com/images/M/MV5BMTUzND...
996,Repulsion,a sex-repulsed woman who disapproves of her si...,https://m.media-amazon.com/images/M/MV5BMzdiZm...
997,Les yeux sans visage,a surgeon causes an accident which leaves his ...,https://m.media-amazon.com/images/M/MV5BNjVjND...
998,Shine,"pianist david helfgott, driven by his father a...",https://m.media-amazon.com/images/M/MV5BNTNlZD...
999,Celda 211,the story of two men on different sides of a p...,https://m.media-amazon.com/images/M/MV5BMjI2OD...

In [31]:
new_df.to_csv('new_df.csv')

In [32]:
!pip install nltk

Requirement already satisfied: nltk in c:\users\nikhi\anaconda3\lib\site-packages (3.7)
Requirement already satisfied: regex>=2021.8.3 in c:\users\nikhi\anaconda3\lib\site-packages (from nltk) (2022.7.9)
Requirement already satisfied: click in c:\users\nikhi\anaconda3\lib\site-packages (from nltk) (8.0.4)
Requirement already satisfied: joblib in c:\users\nikhi\anaconda3\lib\site-packages (from nltk) (1.1.0)
Requirement already satisfied: tqdm in c:\users\nikhi\anaconda3\lib\site-packages (from nltk) (4.64.1)
Requirement already satisfied: colorama in c:\users\nikhi\anaconda3\lib\site-packages (from click->nltk) (0.4.5)

In [33]:
import nltk

In [34]:
from nltk.stem.porter import PorterStemmer
ps  = PorterStemmer()

In [35]:
def stem(text):
    y = []
    
    for i in text.split():
        y.append(ps.stem(i))
    
    return " ".join(y)

In [36]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\nikhi\AppData\Local\Temp\ipykernel_18972\3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

# VECTORISATION

In [37]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 5000 , stop_words = 'english')

In [38]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [39]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [40]:
cv.get_feature_names()

C:\Users\nikhi\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['00',
 '000',
 '007',
 '10',
 '12',
 '1880',
 '1890',
 '18th',
 '1900',
 '1910',
 '1920',
 '1925',
 '1930',
 '1940s',
 '1944',
 '1950',
 '1960',
 '1960s',
 '1962',
 '1963',
 '1968',
 '1970',
 '1970s',
 '1980',
 '1984',
 '1985',
 '1990',
 '1993',
 '1999',
 '20',
 '2001',
 '2013',
 '21',
 '24',
 '30',
 '35',
 '40',
 'aamirkhan',
 'abandon',
 'abil',
 'abl',
 'aboard',
 'abramschrispine',
 'abruptli',
 'abus',
 'accept',
 'accid',
 'accident',
 'accompani',
 'account',
 'accus',
 'achiev',
 'achyuthkumar',
 'acquir',
 'act',
 'action',
 'activ',
 'activist',
 'actor',
 'actress',
 'actual',
 'adapt',
 'addict',
 'adilhussain',
 'adjust',
 'adolf',
 'adopt',
 'adult',
 'adulter',
 'advanc',
 'adventur',
 'adventure',
 'advertis',
 'advisor',
 'affair',
 'affect',
 'africa',
 'african',
 'ag',
 'age',
 'agent',
 'aging',
 'ago',
 'agre',
 'ahead',
 'aid',
 'aimless',
 'akira',
 'akirakurosawatatsuyanakadai',
 'akirakurosawatoshirômifune',
 'alabama',
 'alanarkin',
 'alantudyk',
 'albertbrook',
 'albertfinney',
 'alcohol',
 'alecguinness',
 'alejandrog',
 'alexand',
 'alexandramarialara',
 'alfredhitchcockcarygrant',
 'alfredhitchcockjamesstewart',
 'aliabhatt',
 'alibi',
 'alidavalli',
 'alien',
 'alli',
 'allianc',
 'allies',
 'allow',
 'allur',
 'alon',
 'alongsid',
 'alpacino',
 'alt',
 'altan',
 'alter',
 'aman',
 'amateur',
 'ambiti',
 'america',
 'american',
 'amid',
 'amitabhbachchan',
 'amyadams',
 'anadearmas',
 'anatolian',
 'ancient',
 'andréramiro',
 'angel',
 'angeles',
 'animation',
 'ann',
 'annakendrick',
 'annebancroft',
 'annebaxter',
 'annehathaway',
 'annemoss',
 'anonym',
 'anoth',
 'anoukaimée',
 'ansiba',
 'answer',
 'anthonyedward',
 'anthonyhopkins',
 'anthonyrusso',
 'anthropomorph',
 'anti',
 'anupamkher',
 'anushkashetty',
 'anyon',
 'anyth',
 'aoiyûki',
 'apart',
 'apartment',
 'ape',
 'apocalypt',
 'appear',
 'appoint',
 'approach',
 'approaches',
 'area',
 'argu',
 'aristocrat',
 'arizona',
 'arm',
 'armi',
 'arminmueller',
 'army',
 'arrang',
 'arrest',
 'arriv',
 'arrives',
 'arshadwarsi',
 'art',
 'artist',
 'ascens',
 'ask',
 'aspir',
 'assassin',
 'assault',
 'assembl',
 'assign',
 'assist',
 'assum',
 'astronaut',
 'athlet',
 'attack',
 'attempt',
 'attend',
 'attention',
 'attorney',
 'attract',
 'audreyhepburn',
 'august',
 'aunt',
 'australian',
 'author',
 'authorities',
 'aveng',
 'avengers',
 'aviator',
 'avoid',
 'await',
 'awaken',
 'away',
 'awry',
 'babi',
 'bachelor',
 'backward',
 'bad',
 'baggin',
 'bamboo',
 'band',
 'bandit',
 'bandits',
 'bank',
 'banker',
 'bankrupt',
 'bare',
 'barrier',
 'barrykeoghan',
 'bas',
 'base',
 'basebal',
 'basic',
 'batman',
 'battl',
 'battle',
 'beach',
 'bear',
 'beast',
 'beauti',
 'becam',
 'becaus',
 'becom',
 'bed',
 'befor',
 'befriend',
 'began',
 'begin',
 'behavior',
 'belgium',
 'believ',
 'bell',
 'belov',
 'benaffleck',
 'beneath',
 'benedictcumberbatch',
 'benfoster',
 'bengal',
 'beniciodeltoro',
 'benjaminbratt',
 'benkingsley',
 'berlin',
 'best',
 'betray',
 'better',
 'big',
 'biker',
 'bilbo',
 'billmckinney',
 'billmurray',
 'billnighi',
 'billpaxton',
 'billycrudup',
 'billydeewilliam',
 'billywilderwilliamholden',
 'biograph',
 'biographi',
 'biography',
 'biolog',
 'birth',
 'birthday',
 'bitter',
 'bizarr',
 'black',
 'blackmail',
 'blade',
 'blind',
 'block',
 'blond',
 'blood',
 'bloodi',
 'blossom',
 'blue',
 'blur',
 'board',
 'boat',
 'bob',
 'bodi',
 'body',
 'bomanirani',
 'bomb',
 'bond',
 'bongjoonhosongkang',
 'book',
 'boot',
 'booze',
 'border',
 'bore',
 'born',
 'boss',
 'bosses',
 'boston',
 'bouncer',
 'bound',
 'bounti',
 'bounty',
 'bourn',
 'bout',
 'bowl',
 'box',
 'boxer',
 'boy',
 'boyfriend',
 'bradleycooper',
 'bradpitt',
 'break',
 'brendablethyn',
 'brendangleeson',
 'brian',
 'briandepalmaalpacino',
 'bride',
 'brien',
 'brilliant',
 'bring',
 'british',
 'broadway',
 'brooklyn',
 'brother',
 'brought',
 'brown',
 'brucewillis',
 'bruno',
 'brunokirbi',
 'brutal',
 'bryancranston',
 'brycedallashoward',
 'bu',
 'buddi',
 'budget',
 'build',
 'bulli',
 'bureaucrat',
 'buri',
 'burtreynolds',
 'busi',
 'business',
 'businessman',
 'businessmen',
 'busterkeatonbusterkeaton',
 'cab',
 'cabin',
 'california',
 'camerondiaz',
 'camp',
 'campaign',
 'canadian',
 'cancer',
 'captain',
 'captiv',
 'captor',
 'captur',
 'car',
 'care',
 'career',
 'carl',
 'carpent',
 'carrie',
 'carriefisher',
 'carrol',
 'case',
 'cash',
 'casino',
 'cast',
 'castle',
 'catch',
 'cateblanchett',
 'catherinedeneuve',
 'catherinekeen',
 'catherinekeener',
 'cathol',
 'caught',
 'caus',
 'cave',
 'celin',
 'center',
 'central',
 'centuri',
 'century',
 'challeng',
 'champion',
 'chanc',
 'chang',
 'changchen',
 'chao',
 'charact',
 'charg',
 'charl',
 'charlesbronson',
 'charleschaplincharleschaplin',
 'charleslaughton',
 'charlesvanel',
 'chase',
 'chauffeur',
 'chazzpalminteri',
 'cheat',
 'check',
 'chemic',
 'chicago',
 'chicomarx',
 'chief',
 'child',
 'childhood',
 'children',
 'china',
 'chines',
 'chiwetelejiofor',
 'chloëgracemoretz',
 'chosen',
 'chriscooper',
 'chrisevans',
 'chrishemsworth',
 'chrissarandon',
 'christianbale',
 'christma',
 'christoph',
 'christopherlloyd',
 'christophermintz',
 'christophernolanchristianbale',
 'christopherplumm',
 'christopherplummer',
 'christopherwalken',
 'chronicl',
 'church',
 'cia',
 'ciaránhinds',
 'cinema',
 'circus',
 'citi',
 'citizen',
 'city',
 'civil',
 'claim',
 'clan',
 'clash',
 'class',
 'classic',
 'classmat',
 'classroom',
 'clau',
 'clauderain',
 'clauderains',
 'claudiacardinale',
 'clear',
 'clerk',
 'client',
 'clinteastwoodclinteastwood',
 'cliveowen',
 'clone',
 'close',
 'closer',
 'club',
 'clue',
 'coach',
 'coastal',
 'cobb',
 'code',
 'coerc',
 'cold',
 'colinfarrell',
 'colleagu',
 'collect',
 'collector',
 'colleg',
 'college',
 'collid',
 'colonel',
 'com',
 'coma',
 'come',
 'comedi',
 'comedian',
 'comedy',
 'comic',
 'command',
 'commando',
 'commit',
 'common',
 'commonwealth',
 'commun',
 'compani',
 'companion',
 'compassion',
 'compet',
 'complet',
 'complex',
 'complic',
 'comput',
 'computer',
 'comrad',
 'conceal',
 'concern',
 'concert',
 'conduct',
 'confeder',
 'conflict',
 'confront',
 'connect',
 'connel',
 'connor',
 'consequ',
 'consequences',
 'consid',
 'conspiracy',
 'construct',
 'contend',
 'continu',
 'control',
 'controversi',
 'conveni',
 'convent',
 'convict',
 'convinc',
 'cop',
 'coreyfeldman',
 'corner',
 'corpor',
 'corrupt',
 'corruption',
 'count',
 'countri',
 'country',
 'countrymen',
 'coupl',
 'couple',
 'courag',
 'cours',
 'court',
 'cousin',
 'cover',
 'crafti',
 'craigferguson',
 'crash',
 'creat',
 'creatur',
 'crew',
 'cricket',
 'crime',
 'crimes',
 'crimin',
 'criminal',
 'crisi',
 'critic',
 'crook',
 'cross',
 'crosses',
 'crusad',
 'cruz',
 'culprit',
 'cultur',
 'curs',
 'custodi',
 'customers',
 'cybillshepherd',
 'cyborg',
 'cynic',
 'daili',
 'dakotafanning',
 'damag',
 'damage',
 'dames',
 'damienchazellemilesteller',
 'damienchazelleryangosling',
 'damiánszifrondaríograndinetti',
 'danaandrews',
 'danadelany',
 'danawynter',
 'danaykroyd',
 'danc',
 'dancer',
 'danger',
 'dangilroyjakegyllenhaal',
 'danhicks',
 'daniel',
 'danielauteuil',
 'danielboulanger',
 'danieldur',
 'danielgiménezcacho',
 'danielledarrieux',
 'danielleproulx',
 'danielmays',
 'danielmonzónluistosar',
 'danielribeiroghilhermelobo',
 'danielricht',
 'danielscheinertmichelleyeoh',
 'danielstern',
 'danish',
 'danistanovicbrankodjuric',
 'dankwan',
 'dannyaiello',
 'dannyglover',
 'dant',
 'danub',
 'darasinghrandhawa',
 'darci',
 'darcy',
 'dare',
 'dariusmarderrizahmed',
 'dark',
 'darken',
 'darrenaronofskyellenburstyn',
 'darrenaronofskymickeyrourke',
 'darrenaronofskynatalieportman',
 'darrenmcgavin',
 'darrylf',
 'darth',
 'darylhannah',
 'date',
 'daughter',
 'dave',
 'davebautista',
 'david',
 'davidcarradine',
 'davidfincherbradpitt',
 'davidhand',
 'davidmorse',
 'davido',
 'davidyatesdanielradcliffe',
 'day',
 'days',
 'dea',
 'dead',
 'deadli',
 'deaf',
 'deal',
 'dealer',
 'death',
 'debt',
 'decad',
 'decades',
 'decid',
 'decis',
 'decision',
 'deep',
 'deepli',
 'defeat',
 'defend',
 'defens',
 'dehuman',
 'delhi',
 'deliv',
 'deliveri',
 'delv',
 'demand',
 'demetakbag',
 'demigod',
 'demon',
 'demonstr',
 'denmark',
 'dennishopper',
 'denzelwashington',
 'depict',
 'depress',
 'depression',
 'derekjacobi',
 'descend',
 'desert',
 'design',
 'desir',
 'desper',
 'despit',
 'destroy',
 'destruct',
 'destruction',
 'detect',
 'detective',
 'determin',
 'detroit',
 'devast',
 'develop',
 'devic',
 'devil',
 'devot',
 'diagnos',
 'diamond',
 'dianekeaton',
 'dianekruger',
 'diannewiest',
 'dictat',
 'did',
 'die',
 'dies',
 'differ',
 'differences',
 'difficult',
 'dinner',
 'director',
 'disappear',
 'disast',
 'discov',
 'discoveri',
 'discuss',
 'disease',
 'disfigur',
 'disguis',
 'disillus',
 'dispatch',
 'disrupt',
 'distanc',
 'distant',
 'distress',
 'disturb',
 'divid',
 'divorc',
 'djimonhounsou',
 'doctor',
 'documentari',
 'documentary',
 'doesn',
 'dog',
 'doll',
 'dollar',
 'domhnallgleeson',
 'domin',
 'dominicwest',
 'don',
 'donaldsutherland',
 'donhall',
 'doom',
 'door',
 'doubl',
 'doubt',
 'downward',
 'dr',
 'dragon',
 'drama',
 'dramat',
 'dream',
 'dreams',
 'drift',
 'drifter',
 'drink',
 'drive',
 'driven',
 'driver',
 'drug',
 'drummer',
 'drunk',
 'dublin',
 'dure',
 'dustinhoffman',
 'dysfunct',
 'dystop',
 'earli',
 'earn',
 'earth',
 'east',
 'eccentr',
 'eddi',
 'eddiemurphy',
 'edgarwrightsimonpegg',
 'edharris',
 'editor',
 'edmondo',
 'educ',
 'edward',
 'edwardarnold',
 'edwardfurlong',
 'edwardg',
 'edwardnorton',
 'effort',
 'ego',
 'elabor',
 'elderli',
 'elit',
 'eliwallach',
 'elizabeth',
 'embark',
 'embarrass',
 'embrac',
 'embroil',
 'emerg',
 'emilymortimer',
 'emmastone',
 'emmawatson',
 'emot',
 'emperor',
 'empir',
 'empire',
 'employ',
 'employer',
 'empti',
 'encount',
 'end',
 'endang',
 'endur',
 'enemi',
 'enemies',
 'enforc',
 'engag',
 'engin',
 'england',
 'english',
 'enlist',
 'enrol',
 'ensu',
 'ensur',
 'enter',
 'enterpris',
 'enthral',
 'entir',
 'epic',
 'equip',
 'era',
 'ericbana',
 'erichvonstroheim',
 'erik',
 'ernestborgnine',
 'escal',
 'escap',
 'escape',
 'estat',
 'estrang',
 'ethancoen',
 'ethanhawke',
 'ether',
 'europe',
 'european',
 'evalu',
 'eve',
 'event',
 'eventu',
 'everi',
 'everyon',
 'everyth',
 'evil',
 'ewanmcgregor',
 'ex',
 'exact',
 'examin',
 'execut',
 'exil',
 'exist',
 'existed',
 'expand',
 'expatri',
 'expedit',
 'expel',
 'experi',
 'expert',
 'exploit',
 'explor',
 'expos',
 'exquisit',
 'extraordinari',
 'extraterrestri',
 'extrem',
 'ey',
 'eye',
 'face',
 'fact',
 'fade',
 'fail',
 'fall',
 'fallen',
 'fals',
 'fame',
 'famili',
 'familiar',
 'family',
 'famou',
 'fan',
 'fanat',
 'fantasi',
 'fantasies',
 'fantasy',
 'faraway',
 'farm',
 'farmer',
 'fast',
 'fat',
 'fate',
 'father',
 'favor',
 'fayedunaway',
 'fbi',
 'fear',
 'feder',
 'federicofellinimarcellomastroianni',
 'feel',
 'fellow',
 'femal',
 'feud',
 'fi',
 'fiancé',
 'fiction',
 'fight',
 'fighter',
 'figur',
 'film',
 'filmmak',
 'final',
 'fionnulaflanagan',
 'fish',
 'fledgl',
 'flee',
 'flesh',
 'fli',
 'float',
 'florencepugh',
 'flower',
 'focus',
 'foil',
 'follow',
 'foot',
 'footbal',
 'forc',
 'foreign',
 'forest',
 'forestwhitaker',
 'forev',
 'forever',
 'forg',
 'form',
 'forti',
 'fortress',
 'fortun',
 'fortune',
 'foster',
 'fought',
 'fox',
 'fragil',
 'frame',
 'franc',
 'france',
 'francesmcdormand',
 'francisco',
 'frank',
 'frankcaprajamesstewart',
 'frankenstein',
 'franklinj',
 'frankmorgan',
 'frantic',
 'françoispérier',
 'fre',
 'freak',
 'fredericforrest',
 'fredmacmurray',
 'fredricmarch',
 'free',
 'freedom',
 'french',
 'friend',
 'friends',
 'friendship',
 'frigid',
 'frodo',
 'frozen',
 'frustrat',
 'fuel',
 'fulfil',
 'fund',
 'futur',
 'future',
 'gabrielemuccinowillsmith',
 'gaelgarcíabernal',
 'gain',
 'galaxi',
 'galaxy',
 'game',
 'gandalf',
 'gang',
 'gangster',
 'garethevansikouwais',
 'garyoldman',
 'gather',
 'gay',
 'genarowlands',
 'genehackman',
 'genelockhart',
 'gener',
 'geoffreyrush',
 'georg',
 'georgea',
 'georgec',
 'georgecukor',
 'georgemackay',
 'georgeroyhillpaulnewman',
 'georgesanders',
 'gerardbutler',
 'german',
 'germani',
 'ghetto',
 'ghost',
 'gianmariavolontè',
 'giant',
 'gift',
 'girl',
 ...]

# COSINE SIMILARITY

In [41]:
from sklearn.metrics.pairwise import cosine_similarity

In [42]:
similarity = cosine_similarity(vectors)

In [43]:
similarity

array([[1.        , 0.05547002, 0.05783149, ..., 0.07161149, 0.06201737,
        0.05661385],
       [0.05547002, 1.        , 0.20851441, ..., 0.20655911, 0.13416408,
        0.12247449],
       [0.05783149, 0.20851441, 1.        , ..., 0.10767638, 0.09325048,
        0.12768848],
       ...,
       [0.07161149, 0.20655911, 0.10767638, ..., 1.        , 0.11547005,
        0.05270463],
       [0.06201737, 0.13416408, 0.09325048, ..., 0.11547005, 1.        ,
        0.04564355],
       [0.05661385, 0.12247449, 0.12768848, ..., 0.05270463, 0.04564355,
        1.        ]])

In [44]:
#findinding the index of the movie
new_df[new_df['movie_title'] == 'Avatar'].index[0]

468

In [45]:
sorted(list(enumerate(similarity[0])),reverse=True,key = lambda x : x[1])[1:6]

[(780, 0.20180183819889375),
 (812, 0.1860521018838127),
 (54, 0.17739371879672478),
 (630, 0.16984155512168939),
 (252, 0.16724840200141816)]

In [46]:
def recommend(movie):
    movie_index = new_df[new_df['movie_title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)),reverse=True,key = lambda x : x[1])[1:6]
    
    for i in movies_list:
        print(new_df.iloc[i[0]].movie_title)

In [47]:
recommend('The Dark Knight')

Batman Begins
The Dark Knight Rises
The Batman
Dip huet seung hung
Enter the Dragon

In [48]:
import pickle

In [49]:
pickle.dump(new_df.to_dict(),open('movie_dict.pkl' , 'wb'))

In [50]:
pickle.dump(similarity,open('similarity.pkl' , 'wb'))

In [51]:
new_df['movie_poster'][0]

'https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX67_CR0,0,67,98_AL_.jpg'

In [52]:
new_df[new_df['movie_title'] == "The Godfather"].movie_poster[1]

'https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UY98_CR1,0,67,98_AL_.jpg'

In [53]:
new_df['movie_title'] = new_df['movie_title'].apply(lambda x: x.strip())

C:\Users\nikhi\AppData\Local\Temp\ipykernel_18972\1618321836.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['movie_title'] = new_df['movie_title'].apply(lambda x: x.strip())

In [54]:
new_df['movie_title'][6]

'The Lord of the Rings: The Return of the King'

In [55]:
new_df[new_df['movie_title'] == new_df['movie_title'][678]].movie_poster.values[0]

'https://m.media-amazon.com/images/M/MV5BMTViNjlkYjgtMmE3Zi00ZGVkLTkyMjMtNzc3YzAwNzNiODQ1XkEyXkFqcGdeQXVyMjA0MzYwMDY@._V1_UX67_CR0,0,67,98_AL_.jpg'

#